### ISSUE TITLE
doesn't work on github pages due to security restrictions

### ISSUE THREAD

**Issue by arkarkark** [leocaseiro/AddToDelicious#1]
```
Refused to frame 'https://del.icio.us/save/get_iframe_savelink?url=https%3A//github.com/beard…rdedspice/beardedspice%3A%20Mac%20Media%20Keys%20for%20the%20Masses&notes=' because it violates the following Content Security Policy directive: "child-src render.githubusercontent.com".

(anonymous) @ jquery.min.js:4
access @ jquery.min.js:2
html @ jquery.min.js:4
init @ get_bookmarklet_save?url=https%3A%2F%2Fgithub.com%2Fbeardedspice%2Fbeardedspice&title=beardedspice%…:33
(anonymous) @ get_bookmarklet_save?url=https%3A%2F%2Fgithub.com%2Fbeardedspice%2Fbeardedspice&title=beardedspice%…:42
(anonymous) @ get_bookmarklet_save?url=https%3A%2F%2Fgithub.com%2Fbeardedspice%2Fbeardedspice&title=beardedspice%…:98
```

![image](https://cloud.githubusercontent.com/assets/877895/22563452/7187bac2-e935-11e6-9ad4-675b6380eeb2.png)

good news is there is a workaround!

http://stackoverflow.com/questions/24641592/injecting-iframe-into-page-with-restrictive-content-security-policy/24649134#24649134

**Comment by leocaseiro** [comment]
Hi @arkarkark, thanks for reporting that. I'll try to fix it next week. Thanks for your workaround solution btw.

**Comment by leocaseiro** [comment]
I've just had the same issue today and I realised that was an issue about it.

I'll refactor to use a popup instead of loading in the page.

Thanks again for reporting that.

I'll let some notes for me down here:


https://del.icio.us/save/get_iframe_savelink?url=https%3A//github.com/leocaseiro/AddToDelicious&title=leocaseiro/AddToDelicious%3A%20Chrome%20Extension%20to%20add%20current%20link%20to%20Delicious&notes=

Example popup: https://developer.chrome.com/extensions/examples/tutorials/getstarted/popup.html

**Comment by leocaseiro** [comment]
WARNING: Unfortunately Delicious has been discontinued since June 15, 2017. https://blog.pinboard.in/2017/06/pinboard_acquires_delicious/

I suggest moving from Delicious to Google Bookmarks.

To export use: https://del.icio.us/export
To import use: https://www.google.com/bookmarks/deliciousimport
